sudo: false
language: scala

jdk:
  - openjdk11

before_install:
  - git fetch --tags
  - export PATH=${PATH}:./vendor/bundle

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
    - name: test 2.12
      scala: 2.12.9
      script: sbt ++$TRAVIS_SCALA_VERSION test
    # -
    #   name: mima
    #   script: sbt +mimaReportBinaryIssues
    -
      name: docs
      scala: 2.12.9
      install:
        - rvm use 2.6.0 --install --fuzzy
        - gem update --system
        - gem install sass
        - gem install jekyll -v 3.2.1
      script: sbt ++$TRAVIS_SCALA_VERSION docs/makeMicrosite
    # run ci-release only if previous stages passed
    - stage: release
      name: release
      script: 
        - sbt ci-release
    - stage: release
      name: microsite
      scala: 2.12.9
      install:
        - rvm use 2.6.0 --install --fuzzy
        - gem update --system
        - gem install sass
        - gem install jekyll -v 3.2.1
      script: sbt ++$TRAVIS_SCALA_VERSION docs/publishMicrosite

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt