name: sbt-mima-version-check
baseurl: /sbt-mima-version-check
description: Plugin to Automate which Mima Versions to Check
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.1+17-5ebb786b-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
