name: sbt-mima-version-check
baseurl: /sbt-mima-version-check
description: Plugin to Automate which Mima Versions to Check
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.1+10-2c5d77a8-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
